/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movie;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author steyza
 */
public class Uj_szinesz extends javax.swing.JFrame {

    /**
     * Creates new form Uj_szinesz
     */
    public Uj_szinesz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_nev = new javax.swing.JTextField();
        jtf_cim = new javax.swing.JTextField();
        jLabel_Hossz = new javax.swing.JLabel();
        jLabel_mMufaj = new javax.swing.JLabel();
        jLabel_Hossz1 = new javax.swing.JLabel();
        jButton_Rogzit = new javax.swing.JButton();
        jButton_Vissza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtf_nev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_nev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nevKeyTyped(evt);
            }
        });

        jtf_cim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_cim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_cimKeyTyped(evt);
            }
        });

        jLabel_Hossz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Hossz.setText("Név:");

        jLabel_mMufaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_mMufaj.setText("Cím:");

        jLabel_Hossz1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_Hossz1.setText("Új színész");

        jButton_Rogzit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Rogzit.setText("Rögzít");
        jButton_Rogzit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RogzitActionPerformed(evt);
            }
        });

        jButton_Vissza.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Vissza.setText("Vissza");
        jButton_Vissza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VisszaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Hossz1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_Vissza)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Rogzit))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_mMufaj)
                                .addComponent(jLabel_Hossz))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_nev, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_cim, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_Hossz1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Hossz)
                    .addComponent(jtf_nev, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_cim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_mMufaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Vissza)
                    .addComponent(jButton_Rogzit))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nevKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nevKeyTyped
        
    }//GEN-LAST:event_jtf_nevKeyTyped

    private void jtf_cimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cimKeyTyped
        
    }//GEN-LAST:event_jtf_cimKeyTyped

    private void jButton_RogzitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RogzitActionPerformed
        String nev = jtf_nev.getText();
        String cim = jtf_cim.getText();
        
        try {
            Connection con = MySQL.ConnectDB();
            String sql = "INSERT INTO Szineszek (nev, cim) VALUES (?, ?);";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, nev);
            stmt.setString(2, cim);
            stmt.execute();
            JOptionPane.showMessageDialog(this, "Sikeres felvétel!");
            jtf_nev.setText(null);
            jtf_cim.setText(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton_RogzitActionPerformed

    private void jButton_VisszaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VisszaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_VisszaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uj_szinesz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uj_szinesz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uj_szinesz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uj_szinesz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uj_szinesz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Rogzit;
    private javax.swing.JButton jButton_Vissza;
    private javax.swing.JLabel jLabel_Hossz;
    private javax.swing.JLabel jLabel_Hossz1;
    private javax.swing.JLabel jLabel_mMufaj;
    private javax.swing.JTextField jtf_cim;
    private javax.swing.JTextField jtf_nev;
    // End of variables declaration//GEN-END:variables
}
